// lib/utils/taapdeel_category_rules.dart
import 'package:flutter/foundation.dart';

/// النتيجة النهائية: اسم الفئة + اسم التصنيف الفرعي (لو موجود)
class TaapdeelCategoryMatch {
  final String categoryName;
  final String? subCategoryName;

  const TaapdeelCategoryMatch({
    required this.categoryName,
    this.subCategoryName,
  });

  @override
  String toString() =>
      'TaapdeelCategoryMatch(category=$categoryName, sub=$subCategoryName)';
}

/// تعريف Rule واحد
class TaapdeelCategoryRule {
  final String categoryName;
  final String? subCategoryName;
  final List<String> keywords; // كلمات مفتاحية بالعربي/إنجليزي

  const TaapdeelCategoryRule({
    required this.categoryName,
    required this.subCategoryName,
    required this.keywords,
  });
}

/// جميع الـ rules
class TaapdeelCategoryRules {
  /// 📌 جدول القواعد
  static const List<TaapdeelCategoryRule> _rules = <TaapdeelCategoryRule>[
    // ===========================
    //  أمهات – Emhat
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'امهات',
      subCategoryName: 'ملابس واحذية',
      keywords: <String>[
        // عربي – ملابس عامة
        'فستان',
        'فساتين',
        'dress',
        'بنطلون',
        'بنطلونات',
        'سروال',
        'pants',
        'جيب',
        'تنوره',
        'تنورة',
        'skirt',
        'تيشيرت',
        'تي شيرت',
        'tshirt',
        'هودي',
        'سويت شيرت',
        'بلوزه',
        'بلوزة',
        'بلوز',
        'قميص',
        'شميز',
        'جاكيت',
        'jacket',
        'معطف',
        'coat',
        'عبايه',
        'عباية',
        'جلابية',
        'جلبيه',
        'روب',
        'pajama',
        'بيجامه',
        'بيجاما',
        // أحذية
        'شراب',
        'جوارب',
        'socks',
        'حذاء',
        'احذيه',
        'جزمه',
        'جزمة',
        'بوت',
        'boot',
        'كوتشي',
        'حذاء رياضي',
        'sport shoes',
        'حذاء كعب',
        'heels',
        'شبشب',
        'slippers',
        // gender hints
        'حريمي',
        'رجالي',
        'نسائي',
        'رجال',
        'نساء',
        'ladies',
        'men',
        // مقاسات
        'مقاس',
        'size',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'امهات',
      subCategoryName: 'إكسسوارات',
      keywords: <String>[
        'شنطه',
        'شنطة',
        'شنط',
        'حقيبه',
        'حقيبة',
        'bag',
        'handbag',
        'كلتش',
        'cross bag',
        'حزام',
        'belt',
        'نظاره',
        'نظارة',
        'نظارات',
        'نضاره',
        'نضارة',
        'نظارة شمس',
        'نظارة طبية',
        'sunglasses',
        'glasses',
        'ساعه',
        'ساعة',
        'ساعات',
        'watch',
        'smart watch',
        'bracelet',
        'اسوره',
        'اسورة',
        'اسواره',
        'خاتم',
        'ring',
        'حلق',
        'قرط',
        'earring',
        'قلاده',
        'قلادة',
        'سلسلة',
        'necklace',
        'اكسسوار',
        'اكسسوارات',
        'accessories',
        'محفظه',
        'محفظة',
        'wallet',
        'بروش',
        'brouch',
        'توكة',
        'توكات',
        'مشبك شعر',
        'hair clip',
        'حجاب',
        'طرحه',
        'طرحة',
        'اسكارف',
        'scarf',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'امهات',
      subCategoryName: 'العنايه بالطفل',
      keywords: <String>[
        'ببرونه',
        'ببرونة',
        'بزازه',
        'باطلونه',
        'حفاض',
        'حفاضات',
        'بامبرز',
        'diaper',
        'car seat',
        'كرسي سياره',
        'كرسي عربية',
        'كرسي سيارة',
        'كرسي عربيه',
        'مشاية',
        'مشايه',
        'walker',
        'سرير طفل',
        'سرير اطفال',
        'سرير بيبي',
        'بسرير',
        'سرير هزاز',
        'بيبي',
        'رضيع',
        'مولود',
        'نيو بورن',
        'newborn',
        'رضاعه',
        'رضاعة',
        'شفاط لبن',
        'breast pump',
        'مونيتر بيبي',
        'baby monitor',
        'كرسي اكل',
        'كرسي طعام',
        'high chair',
        'عربة اطفال',
        'عربيه اطفال',
        'عربية اطفال',
        'stroller',
        'سكاتة',
        'تيته',
        'pacifier',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'امهات',
      subCategoryName: 'مستلزمات الطفل',
      keywords: <String>[
        'لبس اطفال',
        'ملابس اطفال',
        'فستان بناتي',
        'بناتي',
        'اولادي',
        'ملابس طفل',
        'بدله اطفال',
        'بدلة اطفال',
        'بدله بيبي',
        'pajama kids',
        'بيجامه اطفال',
        'بيجاما اطفال',
        'حذاء اطفال',
        'جزمه اطفال',
        'كوتشي اطفال',
        'تريننج اطفال',
        'ترينينج اطفال',
        'ترنج',
        'ترينج',
        'سالوبت',
        'salopette',
        'bodysuit',
        'سالوبيت',
        'سنوات',
        'سنه',
        'عمر',
        'age',
        'بيبي بوي',
        'بيبي جيرل',
        'baby boy',
        'baby girl',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'امهات',
      subCategoryName: 'الصحه والجمال',
      keywords: <String>[
        'مكياج',
        'ميك اب',
        'makeup',
        'روج',
        'lipstick',
        'كحل',
        'eyeliner',
        'ماسكارا',
        'blusher',
        'بودره',
        'powder',
        'فانديشن',
        'foundation',
        'كريم',
        'مرطب',
        'مرطب شفاه',
        'lip balm',
        'skin care',
        'عنايه بالبشره',
        'عناية بالبشرة',
        'سيروم',
        'serum',
        'برفان',
        'عطر',
        'perfume',
        'لوشن',
        'body lotion',
        'شامبو',
        'بلسم',
        'ماسكات',
        'ماسك',
        'غسول',
        'wash face',
        'صابون طبي',
      ],
    ),

    // ===========================
    //  المنزل – Home
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'المنزل',
      subCategoryName: 'ديكور المنزل',
      keywords: <String>[
        'لوحه',
        'لوحة',
        'تابلوه',
        'برواز',
        'فازه',
        'فازة',
        'مزهرية',
        'flower vase',
        'مفرش',
        'مفارش',
        'runner',
        'ستاره',
        'ستارة',
        'ستائر',
        'curtain',
        'سجاد',
        'سجاده',
        'carpet',
        'rug',
        'ديكور',
        'decor',
        'وساده',
        'وسادة',
        'مخده',
        'مخدة',
        'pillow',
        'cushion',
        'اباجوره',
        'اباجورة',
        'lamp',
        'table lamp',
        'لوحة حائط',
        'wall art',
        'شمعدان',
        'شموع',
        'candles',
        'نجفه',
        'نجفة',
        'chandelier',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'المنزل',
      subCategoryName: 'المطبخ والمائده',
      keywords: <String>[
        'طقم اكل',
        'طقم اطباق',
        'طقم حلل',
        'طقم صيني',
        'صينيه',
        'صينية',
        'tray',
        'معالق',
        'ملاعق',
        'شوك',
        'fork',
        'ملعقه',
        'ملعقة',
        'سكاكين',
        'knife',
        'كبايات',
        'اكواب',
        'كوب',
        'كاسات',
        'mug',
        'حلل',
        'حله',
        'قدر',
        'طاسه',
        'طاسة',
        'مقلاه',
        'مقلاة',
        'قدره',
        'قِدر',
        'طقم مجات',
        'طقم كسات',
        'مطبخ',
        'kitchen',
        'لوحات مطبخ',
        'طقم توابل',
        'علب توابل',
        'حافظة طعام',
        'صندوق غداء',
        'حلة ضغط',
        'pressure cooker',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'المنزل',
      subCategoryName: 'اجهزه منزليه',
      keywords: <String>[
        'ثلاجه',
        'ثلاجة',
        'ديب فريزر',
        'deep freezer',
        'غساله',
        'غسالة',
        'ميكرويف',
        'microwave',
        'بوتجاز',
        'بوتاجاز',
        'فرن',
        'oven',
        'غسالة اطباق',
        'غسالة أطباق',
        'dishwasher',
        'مكنسه',
        'مكنسة',
        'vacuum',
        'مروحه',
        'مروحة',
        'fan',
        'دفايه',
        'دفاية',
        'heater',
        'air fryer',
        'خلاط',
        'blender',
        'محضر طعام',
        'food processor',
        'محضر قهوة',
        'coffeemaker',
        'غلاية',
        'kettle',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'المنزل',
      subCategoryName: 'الحديقه بالمنزل',
      keywords: <String>[
        'نباتات',
        'نبات',
        'زرع',
        'شتله',
        'شتلة',
        'garden',
        'حديقة',
        'اصيص',
        'اصيص زرع',
        'pot',
        'flower pot',
        'شبكه ري',
        'شبكة ري',
        'خرطوم',
        'خرطوم مياه',
        'مرجيحه حديقة',
        'مقعد حديقة',
        'garden chair',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'المنزل',
      subCategoryName: 'بين باج',
      keywords: <String>[
        'بين باج',
        'bean bag',
        'كرسي كيس',
        'كرسي بين باج',
        'صوفا باج',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'المنزل',
      subCategoryName: 'شنط سفر',
      keywords: <String>[
        'شنطه سفر',
        'شنطة سفر',
        'شنط سفر',
        'حقيبه سفر',
        'حقيبة سفر',
        'travel bag',
        'سوست كيس',
        'شنطة ترولي',
        'trolley bag',
        'حقيبة كبينة',
        'كابينه',
        'carry on',
        'حقيبة ظهر سفر',
      ],
    ),

    // ===========================
    //   أدوات مدرسية – School
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'ادوات مدرسية',
      subCategoryName: 'شنط مدرسية',
      keywords: <String>[
        'شنطه مدرسه',
        'شنطه مدرسية',
        'شنطة مدرسية',
        'school bag',
        'school backpack',
        'backpack',
        'حقيبة مدرسية',
        'لانش بوكس',
        'لانش بوكس',
        'lunch box',
        'شنطة لانش',
        'زمزميه',
        'زمزمية',
        'zamaza',
        'zamaza',
        'water bottle',
        'زجاجة مياه',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'ادوات مدرسية',
      subCategoryName: 'ادوات مكتبيه',
      keywords: <String>[
        'اقلام',
        'قلم',
        'قلم جاف',
        'قلم رصاص',
        'pen',
        'pencil',
        'مسطره',
        'مسطرة',
        'برايه',
        'براية',
        'ممحاه',
        'استيكة',
        'استيكه',
        'eraser',
        'دفتر',
        'كشكول',
        'نوت بوك',
        'notebook',
        'clipboard',
        'highlighter',
        'marker',
        'ملفات',
        'فايل',
        'file',
        'ستابيللو',
        'مقلمة',
        'مقلمه',
        'pencil case',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'ادوات مدرسية',
      subCategoryName: 'كتب مدرسية وخارجية',
      keywords: <String>[
        'كتاب مدرسى',
        'كتاب مدرسي',
        'كتاب خارجي',
        'مذكره',
        'مذكرة',
        'ملازم',
        'revision',
        'مراجعه',
        'مراجعة',
        'guide book',
        'workbook',
        'كراسة انشطة',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'ادوات مدرسية',
      subCategoryName: 'الزي المدرسي',
      keywords: <String>[
        'يونيفورم',
        'زي مدرسي',
        'زي مدرسى',
        'school uniform',
        'تيشيرت مدرسه',
        'تيشيرت مدرسية',
        'بنطلون مدرسه',
        'جاكيت مدرسة',
        'ترنج مدرسة',
      ],
    ),

    // ===========================
    //  هوايات ومهن – Hobbies & Jobs
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'هوايات ومهن',
      subCategoryName: 'اشغال يدويه',
      keywords: <String>[
        'تطريز',
        'كروشية',
        'كروشيه',
        'crochet',
        'tricot',
        'knitting',
        'حياكه',
        'حياكة',
        'خيط',
        'خيوط',
        'خرز',
        'resin',
        'فن يدوي',
        'اعمال يدويه',
        'handmade',
        'فن كروشيه',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'هوايات ومهن',
      subCategoryName: 'صيد',
      keywords: <String>[
        'عدة صيد',
        'عدة صياط',
        'شنطة صيد',
        'سناره',
        'سنارة',
        'طعم',
        'fishing',
        'casting',
        'خيط صيد',
        'بوصة صيد',
        'reel',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'هوايات ومهن',
      subCategoryName: 'فنون',
      keywords: <String>[
        'رسم',
        'لوحه رسم',
        'لوحة رسم',
        'الوان',
        'اركليرك',
        'acrylic',
        'oil color',
        'canvas',
        'كانفس',
        'فرشاه',
        'فرش',
        'فرش رسم',
        'pastel',
        'الوان زيت',
        'الوان مائية',
        'watercolor',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'هوايات ومهن',
      subCategoryName: 'هندسه',
      keywords: <String>[
        'عدة هندسية',
        'مسطرة حرف',
        'مسطرة t',
        'برجل',
        'مثلثات هندسية',
        'ruler set',
        'ruler',
        'رسم هندسي',
        'engineering tools',
        'اسكتش هندسي',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'هوايات ومهن',
      subCategoryName: 'ادوات طبيه',
      keywords: <String>[
        'سماعه طبيب',
        'stethoscope',
        'ضغط',
        'جهاز ضغط',
        'جلوكوميتر',
        'جهاز سكر',
        'medical',
        'medical tool',
        'thermometer',
        'ميزان حراره',
      ],
    ),

    // ===========================
    //  كتب – Books
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'روايات وقصص',
      keywords: <String>[
        'روايه',
        'روايات',
        'novel',
        'قصة',
        'قصص',
        'story',
        'خيال علمي',
        'romance',
        'رعب',
        'اكشن',
        'action novel',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'كتب اسلامية',
      keywords: <String>[
        'اسلامي',
        'اسلاميه',
        'اسلامية',
        'حديث',
        'سيره',
        'سيرة',
        'فقه',
        'تفسير',
        'قران',
        'quran',
        'سيرة نبوية',
        'كتب دينية',
        'religion',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'تطوير الذات والاداريه',
      keywords: <String>[
        'تطوير الذات',
        'self development',
        'self-help',
        'تنميه بشريه',
        'تنمية بشرية',
        'اداره',
        'إدارة',
        'management',
        'قياده',
        'leadership',
        'productivity',
        'time management',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'كتب للاطفال',
      keywords: <String>[
        'قصة اطفال',
        'كتب اطفال',
        'قصص اطفال',
        'picture book',
        'حكايات',
        'حواديت',
        'قصص قبل النوم',
        'kids story',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'لغات',
      keywords: <String>[
        'جرامر',
        'grammar',
        'لغة انجليزية',
        'انجليزي',
        'english course',
        'قاموس',
        'dictionary',
        'لغة المانية',
        'الماني',
        'فرنسي',
        'فرنساوي',
        'spanish',
        'italian',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'العلوم',
      keywords: <String>[
        'فيزياء',
        'كيمياء',
        'احياء',
        'أحياء',
        'رياضيات',
        'math',
        'science',
        'biology',
        'physics',
        'chemistry',
        'geology',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'كتب',
      subCategoryName: 'الكمبيوتر والتكنولوجيا',
      keywords: <String>[
        'برمجه',
        'برمجة',
        'programming',
        'python',
        'java',
        'c#',
        'c++',
        'computers',
        'network',
        'شبكات',
        'امن معلومات',
        'أمن معلومات',
        'cyber',
        'cyber security',
        'database',
        'sql',
      ],
    ),

    // ===========================
    //  إلكترونيات – Electronics
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'الكترونيات',
      subCategoryName: 'اجهزة',
      keywords: <String>[
        'موبايل',
        'موبيل',
        'جوال',
        'تليفون',
        'phone',
        'mobile',
        'هاتف',
        'smartphone',
        'tablet',
        'تابلت',
        'ipad',
        'آيباد',
        'لاب توب',
        'laptop',
        'notebook pc',
        'شاشه',
        'شاشة',
        'تلفزيون',
        'tv',
        'smart tv',
        'ريسيفر',
        'receiver',
        'راوتر',
        'router',
        'بروجيكتور',
        'projector',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'الكترونيات',
      subCategoryName: 'اكسسوارات',
      keywords: <String>[
        'سماعه',
        'سماعات',
        'headphone',
        'earbuds',
        'earphones',
        'bluetooth',
        'كابل',
        'وصله',
        'usb',
        'hdmi',
        'شاحن',
        'charger',
        'شاحن متنقل',
        'power bank',
        'كفر',
        'cover',
        'جراب',
        'screen protector',
        'اسكرينه',
        'اسكرينة',
        'حامل موبايل',
        'mobile holder',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'الكترونيات',
      subCategoryName: 'خطوط',
      keywords: <String>[
        'خط فودافون',
        'خط اورنج',
        'خط اتصالات',
        'sim',
        'sim card',
        'line',
        'خط موبايل',
        'خط موبيل',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'الكترونيات',
      subCategoryName: 'كاميرات',
      keywords: <String>[
        'كاميرا',
        'كاميرات',
        'عدسه',
        'عدسة',
        'dslr',
        'canon',
        'nikon',
        'gopro',
        'كاميرا مراقبة',
        'كاميرا مراقبه',
        'webcam',
      ],
    ),

    // ===========================
    //  ألعاب – Games
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'عجل',
      keywords: <String>[
        'عجله',
        'عجلة',
        'بسكليت',
        'bicycle',
        'bike',
        'دراجه',
        'دراجة',
        'tricycle',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'ليجو وبازل',
      keywords: <String>[
        'ليجو',
        'lego',
        'بازل',
        'puzzle',
        'مكعبات',
        'blocks',
        'مكعبات تركيب',
        'building blocks',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'العاب المناطق الخارجيه',
      keywords: <String>[
        'زحليقه',
        'زحليقة',
        'مرجيحه',
        'مرجيحة',
        'trampoline',
        'ترمبولين',
        'حديقه لعب',
        'playground',
        'بيت لعب',
        'play house',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'العاب البنات',
      keywords: <String>[
        'عروسه',
        'عروسة',
        'باربي',
        'barbie',
        'doll',
        'مطبخ اطفال',
        'مطبخ أطفال',
        'مكياج اطفال',
        'مكياج أطفال',
        'عربة اطفال لعب',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'سكوترات',
      keywords: <String>[
        'سكوتر',
        'scooter',
        'هوفر بورد',
        'hoverboard',
        'skate',
        'اسكيت',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'العاب تحكم عن بعد',
      keywords: <String>[
        'ريموت كنترول',
        'remote control',
        'drone',
        'درون',
        'سياره بالريموت',
        'سيارة ريموت',
        'طائرة ريموت',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'العاب تعليميه',
      keywords: <String>[
        'تعليمي',
        'تعليمية',
        'منتسوري',
        'montessori',
        'stem',
        'تعلم',
        'تعلم الأرقام',
        'تعلم الحروف',
        'لوح تعليمي',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'العاب',
      subCategoryName: 'بلاي ستيشن',
      keywords: <String>[
        'بلاي ستيشن',
        'بلايستيشن',
        'playstation',
        'ps5',
        'ps4',
        'xbox',
        'game disc',
        'شريط لعبة',
        'gaming console',
      ],
    ),

    // ===========================
    //  رياضة – Sports
    // ===========================
    TaapdeelCategoryRule(
      categoryName: 'رياضة',
      subCategoryName: 'ادوات سباحه',
      keywords: <String>[
        'مايوه',
        'مايوه سباحه',
        'بدلة سباحة',
        'بدله سباحه',
        'نظارة سباحه',
        'نظارة سباحة',
        'نظارة سباحه اطفال',
        'شنكل',
        'flippers',
        'floater',
        'armband',
        'عوامه',
        'عوامة',
        'سباحه',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'رياضة',
      subCategoryName: 'اسكواش',
      keywords: <String>[
        'اسكواش',
        'squash',
        'مضرب اسكواش',
        'راكت اسكواش',
        'كرة اسكواش',
        'squash ball',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'رياضة',
      subCategoryName: 'تنس',
      keywords: <String>[
        'tennis',
        'تنس',
        'مضرب تنس',
        'راكت تنس',
        'كرة تنس',
        'tennis ball',
      ],
    ),
    TaapdeelCategoryRule(
      categoryName: 'رياضة',
      subCategoryName: 'اجهزه رياضيه',
      keywords: <String>[
        'اوربتراك',
        'treadmill',
        'مشاية كهرباء',
        'جهاز جيم',
        'جهاز رياضي',
        'دمبل',
        'اوزان',
        'barbell',
        'bench',
        'multi gym',
        'سايكل',
        'دراجة رياضية',
        'يوجا مات',
        'yoga mat',
      ],
    ),
  ];

  /// 🔍 دالة الاقتراح الرئيسية
  static TaapdeelCategoryMatch? suggestFromTitle(String rawTitle) {
    final String title = _normalize(rawTitle);
    if (title.isEmpty) return null;

    TaapdeelCategoryRule? bestRule;
    int bestScore = 0;

    for (final TaapdeelCategoryRule rule in _rules) {
      int score = 0;

      for (final String kw in rule.keywords) {
        if (title.contains(_normalize(kw))) {
          score++;
        }
      }

      if (score > bestScore) {
        bestScore = score;
        bestRule = rule;
      }
    }

    if (bestRule == null || bestScore == 0) {
      return null;
    }

    if (kDebugMode) {
      debugPrint('Taapdeel auto-category → $bestRule (score=$bestScore)');
    }

    return TaapdeelCategoryMatch(
      categoryName: bestRule.categoryName,
      subCategoryName: bestRule.subCategoryName,
    );
  }

  /// تطبيع النص: حروف موحدة + lowercase + إزالة الرموز
  static String _normalize(String input) {
    final String lowered = input.toLowerCase();
    final String normalizedArabic = lowered
        .replaceAll('أ', 'ا')
        .replaceAll('إ', 'ا')
        .replaceAll('آ', 'ا')
        .replaceAll('ى', 'ي')
        .replaceAll('ة', 'ه');

    final String cleaned = normalizedArabic
        .replaceAll(RegExp(r'[^a-z0-9\u0600-\u06FF ]'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();

    return cleaned;
  }
}
