name: Build iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          rm -rf Pods
          rm -rf .symlinks
          rm -f Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS without codesign
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios/iphoneos
